name: Run meta pytest suite on repo

on:
  pull_request:
  push:

jobs:
  run-test:
    if: ${{ endsWith(github.repository, '-auto-template')  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install cookiecutter
        run: pip install pytest cookiecutter poetry

      - name: run pytest
        run: python -m pytest